options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _VERSION: '0.0.0'

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Pegar versão do package.json
        _VERSION=$(node -p "require('./package.json').version")
        echo "Versão detectada: $VERSION"

        # Criar pasta da versão no bucket e subir os arquivos
        gsutil -m cp -r build/* gs://teste-415119.appspot.com/$VERSION/
