options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Pegar versão do package.json
        VERSION=$(\
        cat package.json \
        | grep --only-matching '"version": "[^"]*' \
        | cut --delimiter='"' --fields=4)
        echo "Versão detectada: $${VERSION}"

        # Criar pasta da versão no bucket e subir os arquivos
        gsutil -m cp -r build/* gs://teste-415119.appspot.com/$${VERSION}/
